version: "3.8"
services:

    # PHP Service
    app:
        build:
            context: .
            args:
                - APP_ENV=${APP_ENV}
            dockerfile: Dockerfile
        container_name: laravel_app
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 9000:9000
        depends_on:
            - database

    # Database Server
    database:
        image: mysql:8.0
        ports:
            -   3303:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=${DB_DATABASE}
        volumes:
            - db-data:/var/lib/mysql

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./:/var/www
        depends_on:
            - app

volumes:
    db-data: ~
